name: Deploy Review App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_ORG: personal

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/fly-pr-review-apps@1.2.0

      - name: Verify Fly.io Authentication
        run: flyctl auth whoami
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Set up app name
        id: setup_app_name
        run: echo "FLY_APP_NAME=pr-${{ github.event.number }}-${{ github.repository_owner }}-${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Deploy to Fly.io
        id: deploy
        run: flyctl deploy --remote-only --app ${{ env.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}